export const TaskConstants = {
  UPDATE_NAME: "UPDATE_NAME",
  UPDATE_NAME_START: "UPDATE_NAME_START",
  UPDATE_NAME_COMPLETE: "UPDATE_NAME_COMPLETE",
  UPLOAD_IMAGE_FILE : "UPLOAD_IMAGE_FILE",
  UPLOAD_IMAGE_ANITAION : "UPLOAD_IMAGE_ANITAION",
  UPLOAD_IMAGE_FILE_SUCESS : "UPLOAD_IMAGE_FILE_SUCESS",
  UPLOAD_IMAGE_ANITAION_SUCESS : "UPLOAD_IMAGE_ANITAION_SUCESS",
  SAVE_SELECTED_IMG_ID : "SAVE_SELECTED_IMG_ID",
  SAVE_IMG_Annotation : "SAVE_IMG_Annotation"
};
